import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/ThemeProvider";
import { ClerkProvider } from "@clerk/nextjs";
import QueryProvider from "@/components/QueryProvider";
import { Toaster } from "react-hot-toast";
import { SyncUser } from "./actions/users/SyncUser";

const geistSans = Geist({
     variable: "--font-geist-sans",
     subsets: ["latin"],
});

const geistMono = Geist_Mono({
     variable: "--font-geist-mono",
     subsets: ["latin"],
});

export const metadata: Metadata = {
     title: "Poultry E-Commerce",
     description: "Generated by create next app",
};

export default function RootLayout({
     children,
}: Readonly<{
     children: React.ReactNode;
}>) {
     return (
          <ClerkProvider>
               <html lang="en" suppressHydrationWarning={true}>
                    <body
                         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                    >
                         <ThemeProvider
                              attribute="class"
                              defaultTheme="system"
                              enableSystem
                              disableTransitionOnChange
                         >
                              <QueryProvider>
                                   <div>
                                        <Navbar />

                                        {children}
                                   </div>
                              </QueryProvider>

                              <Toaster />
                         </ThemeProvider>
                    </body>
               </html>
          </ClerkProvider>
     );
}
