export const dummyProducts = [
     {
          id: "1",
          productName: "Large Brown Eggs",
          productSize: "Large",
          stock: 100,
          price: 5.99,
     },
     {
          id: "2",
          productName: "Medium White Eggs",
          productSize: "Medium",
          stock: 150,
          price: 4.99,
     },
     {
          id: "3",
          productName: "Small Quail Eggs",
          productSize: "Small",
          stock: 200,
          price: 3.49,
     },
     {
          id: "4",
          productName: "Organic Free-Range Eggs",
          productSize: "Large",
          stock: 80,
          price: 7.99,
     },
     {
          id: "5",
          productName: "Duck Eggs",
          productSize: "Large",
          stock: 50,
          price: 6.49,
     },
     {
          id: "6",
          productName: "Farm Fresh Eggs",
          productSize: "Medium",
          stock: 120,
          price: 5.49,
     },
     {
          id: "7",
          productName: "Extra Large Brown Eggs",
          productSize: "Extra Large",
          stock: 90,
          price: 6.99,
     },
     {
          id: "8",
          productName: "Pasture-Raised Eggs",
          productSize: "Large",
          stock: 70,
          price: 8.49,
     },
     {
          id: "9",
          productName: "Cage-Free Eggs",
          productSize: "Medium",
          stock: 110,
          price: 6.29,
     },
     {
          id: "10",
          productName: "Omega-3 Enriched Eggs",
          productSize: "Large",
          stock: 60,
          price: 9.99,
     },
     {
          id: "11",
          productName: "Soy-Free Organic Eggs",
          productSize: "Large",
          stock: 40,
          price: 10.49,
     },
     {
          id: "12",
          productName: "Heritage Breed Eggs",
          productSize: "Medium",
          stock: 55,
          price: 11.99,
     },
     {
          id: "13",
          productName: "Golden Yolk Eggs",
          productSize: "Large",
          stock: 85,
          price: 7.49,
     },
     {
          id: "14",
          productName: "Speckled Brown Eggs",
          productSize: "Medium",
          stock: 95,
          price: 6.79,
     },
     {
          id: "15",
          productName: "Blue Shell Eggs",
          productSize: "Small",
          stock: 130,
          price: 5.99,
     },
     {
          id: "16",
          productName: "Corn-Fed Chicken Eggs",
          productSize: "Large",
          stock: 75,
          price: 6.89,
     },
     {
          id: "17",
          productName: "Hormone-Free Eggs",
          productSize: "Medium",
          stock: 100,
          price: 5.59,
     },
     {
          id: "18",
          productName: "Vitamin D Enriched Eggs",
          productSize: "Large",
          stock: 65,
          price: 9.29,
     },
     {
          id: "19",
          productName: "White Duck Eggs",
          productSize: "Large",
          stock: 45,
          price: 7.99,
     },
     {
          id: "20",
          productName: "Golden Farm Quail Eggs",
          productSize: "Small",
          stock: 150,
          price: 4.29,
     },
];
